spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: amresh1998
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: amresh
