spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      keepalive-time: 100000
      maximum-pool-size: 100
      minimum-idle: 10
    password: amresh1998
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: amresh
    
